
#nucleotides
A_NORMAL : "./images/a_nucleo.png"
U_NORMAL : "./images/u_nucleo.png"
C_NORMAL : "./images/c_nucleo.png"
G_NORMAL : "./images/g_nucleo.png"
A_UPSIDEDOWN : "./images/a_antinucleo.png"
U_UPSIDEDOWN : "./images/u_antinucleo.png"
C_UPSIDEDOWN : "./images/c_antinucleo.png"
G_UPSIDEDOWN : "./images/g_antinucleo.png"

#ribosomes
SMALL_RIBOSOME : "./images/small_ribosome.png"
BIG_RIBOSOME : "./images/big_ribosome.png"

#mRNA matrix and tRNA
MRNA_CAP : "./images/utr5cap.png"
MRNA : "./images/mRNA.png"
TRNA : "./images/trna.png"

#aminoacids
ALANINE : "./images/alanine.png"
ARGININE : "./images/arginine.png"
ASPARAGINE : "./images/asparagine.png"
ASPARTIC_ACID : "./images/aspartic_acid.png"
CYSTEINE : "./images/cysteine.png"
GLUTAMIC_ACID : "./images/glutamic_acid.png"
GLUTAMINE : "./images/glutamine.png"
GLYCINE : "./images/glycine.png"
HISTIDINE : "./images/histidine.png"
ISOLEUCINE : "./images/isoleucine.png"
LEUCINE : "./images/leucine.png"
LYSINE : "./images/lysine.png"
METHIONINE : "./images/methionine.png"
PHENYLALANINE : "./images/phenylalanine.png"
PROLINE : "./images/proline.png"
SERINE : "./images/serine.png"
THREONINE : "./images/threonine.png"
TRYPTOPHAN : "./images/tryptophan.png"
TYROSINE : "./images/tyrosine.png"
VALINE : "./images/valine.png"